[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
command = "tuigreet --cmd hyprland --time --time-format '%d/%m/%Y - %H:%M' --remember --remember-session --asterisks --container-padding 2 --width 70 --sessions /usr/share/wayland-sessions --power-shutdown 'systemctl poweroff' --power-reboot 'systemctl reboot'"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
